version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=covidmeter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend/covidmeter/
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/covidmeter/.env
    volumes:
      - .:/backend/covidmeter
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: npm start
    volumes:
      - .:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
